# 2. S3 버킷으로 index.html 업로드
      - name: Upload to S3
        run: |
          # 변수와 경로를 따옴표로 감싸서 공백 에러를 방지합니다.
          aws s3 cp index.html "s3://${{ secrets.S3_BUCKET_NAME }}/index.html"

      # 3. EC2에 접속해서 S3로부터 파일 다운로드
      - name: Deploy to EC2 from S3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secreㄹts.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # EC2에서도 동일하게 S3 파일을 가져옵니다.
            aws s3 cp "s3://${{ secrets.S3_BUCKET_NAME }}/index.html" /usr/share/nginx/html/index.html